Update flutter-nightly.yml

diff --git a/.github/workflows/flutter-nightly.yml b/.github/workflows/flutter-nightly.yml
--- a/.github/workflows/flutter-nightly.yml
+++ b/.github/workflows/flutter-nightly.yml
@@ -1,59 +1,40 @@
-name: Flutter Build for Android
+name: Build APK
 
 on:
   push:
     branches:
-      - main
-  workflow_dispatch:
+      - main # Ou qualquer outra branch que você deseja monitorar
+  pull_request:
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Set up JDK
-        uses: actions/setup-java@v1
-        with:
-          java-version: '11'
+    - name: Set up JDK
+      uses: actions/setup-java@v2
+      with:
+        java-version: '11' # Use a versão do JDK que você precisa
 
-      - name: Set up Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: "3.24.4"
+    - name: Set up Flutter
+      uses: subosito/flutter-action@v2
+      with:
+        flutter-version: '3.24.4' # Especifique a versão do Flutter que você está usando
 
-      - name: Check Flutter version
-        run: flutter --version
+    - name: Install dependencies
+      run: flutter pub get
 
-      - name: Install dependencies
-        run: |
-          if [ -d "./flutter" ]; then
-            cd flutter
-            flutter pub get
-          elif [ -d "rustdesk/flutter" ]; then
-            cd rustdesk/flutter
-            flutter pub get
-          else
-            echo "Directory flutter or rustdesk/flutter not found"
-            exit 1
-          fi
-
-      - name: Build APK with Debug Logging
-        run: |
-          if [ -d "./flutter" ]; then
-            cd flutter
-          elif [ -d "rustdesk/flutter" ]; then
-            cd rustdesk/flutter
-          else
-            echo "Directory flutter or rustdesk/flutter not found"
-            exit 1
-          fi
-          flutter build apk --release --verbose --no-tree-shake-icons --build-number=1
-
-      - name: Upload APK
-        uses: actions/upload-artifact@v3
-        with:
-          name: rustdesk-apk
-          path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
+    - name: Build APK
+      run: |
+        if [ -d "./flutter" ]; then
+          cd flutter
+        elif [ -d "rustdesk/flutter" ]; then
+          cd rustdesk/flutter
+        else
+          echo "Directory flutter or rustdesk/flutter not found"
+          exit 1
+        fi
+        flutter build apk --release --verbose --no-tree-shake-icons --warning-mode all
