Update flutter-nightly.yml

diff --git a/.github/workflows/flutter-nightly.yml b/.github/workflows/flutter-nightly.yml
--- a/.github/workflows/flutter-nightly.yml
+++ b/.github/workflows/flutter-nightly.yml
@@ -13,8 +13,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-        with:
-          submodules: true  # Inclui submódulos, se houver
 
       - name: Set up JDK
         uses: actions/setup-java@v1
@@ -32,28 +30,42 @@ jobs:
       - name: Check Dart version
         run: dart --version
 
+      # Instalar dependências do sistema
+      - name: Install system dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y clang cmake gcc g++ curl git libgtk-3-dev libnotify-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libssl-dev pkg-config
+
+      # Listar a estrutura do projeto para verificar o caminho correto
       - name: List project directories
         run: |
           echo "Listing project directory structure:"
           ls -R
+        continue-on-error: true  # Permitir que o processo continue mesmo que a listagem falhe
 
-      - name: Ensure flutter directory exists
+      # Instalar dependências do Flutter
+      - name: Install Flutter dependencies
         run: |
-          if [ ! -d "rustdesk/flutter" ]; then
-            echo "Error: Directory rustdesk/flutter not found!"
+          if [ -d "rustdesk/flutter" ]; then
+            cd rustdesk/flutter
+            flutter pub get
+          else
+            echo "Directory rustdesk/flutter not found"
             exit 1
           fi
 
-      - name: Install dependencies
-        run: |
-          cd rustdesk/flutter
-          flutter pub get
-
+      # Compilar o APK
       - name: Build APK
         run: |
-          cd rustdesk/flutter
-          flutter build apk --release
+          if [ -d "rustdesk/flutter" ]; then
+            cd rustdesk/flutter
+            flutter build apk --release
+          else
+            echo "Directory rustdesk/flutter not found"
+            exit 1
+          fi
 
+      # Upload do APK
       - name: Upload APK
         uses: actions/upload-artifact@v3
         with:
